// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	iam "github.com/aws/aws-sdk-go-v2/service/iam"

	mock "github.com/stretchr/testify/mock"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"

	sts "github.com/aws/aws-sdk-go-v2/service/sts"
)

// AwsProvider is an autogenerated mock type for the AwsProvider type
type AwsProvider struct {
	mock.Mock
}

// EC2Client provides a mock function with given fields:
func (_m *AwsProvider) EC2Client() *ec2.Client {
	ret := _m.Called()

	var r0 *ec2.Client
	if rf, ok := ret.Get(0).(func() *ec2.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ec2.Client)
		}
	}

	return r0
}

// IAMClient provides a mock function with given fields:
func (_m *AwsProvider) IAMClient() *iam.Client {
	ret := _m.Called()

	var r0 *iam.Client
	if rf, ok := ret.Get(0).(func() *iam.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iam.Client)
		}
	}

	return r0
}

// IsAuthenticated provides a mock function with given fields:
func (_m *AwsProvider) IsAuthenticated() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// S3Client provides a mock function with given fields:
func (_m *AwsProvider) S3Client() *s3.Client {
	ret := _m.Called()

	var r0 *s3.Client
	if rf, ok := ret.Get(0).(func() *s3.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.Client)
		}
	}

	return r0
}

// STSClient provides a mock function with given fields:
func (_m *AwsProvider) STSClient() *sts.Client {
	ret := _m.Called()

	var r0 *sts.Client
	if rf, ok := ret.Get(0).(func() *sts.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sts.Client)
		}
	}

	return r0
}
