// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	providers "github.com/datadog/stratus-red-team/internal/providers"
	mock "github.com/stretchr/testify/mock"
)

// StratusProvider is an autogenerated mock type for the StratusProvider type
type StratusProvider struct {
	mock.Mock
}

// GetAwsProvider provides a mock function with given fields:
func (_m *StratusProvider) GetAwsProvider() providers.AwsProvider {
	ret := _m.Called()

	var r0 providers.AwsProvider
	if rf, ok := ret.Get(0).(func() providers.AwsProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(providers.AwsProvider)
		}
	}

	return r0
}
